In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
def feature_scaling(X):
    # 1. Calculamos el máximo por columna
    x_max = np.max(X, axis=0) 
    
    # 2. Corrección: Evitar división por cero si el máximo es 0
    x_max_copy = np.copy(x_max)
    x_max_copy[x_max_copy == 0] = 1 
    
    # 3. Aplicamos división (Broadcasting)
    X_scaled = X / x_max_copy
    
    return X_scaled, x_max

# Datos: [Tamaño (pies2), Cuartos, Antigüedad (años)]
X = np.array([
    [2104, 5, 45],
    [1416, 3, 40],
    [1534, 3, 30],
    [852, 2, 36]
])

valores_reescalados, valores_maximos = feature_scaling(X)

print("Datos originales:\n", X)
print("Datos escalados:\n", valores_reescalados)
print("valores maximos de cada caracteristica:\n", valores_maximos)

Datos originales:
 [[2104    5   45]
 [1416    3   40]
 [1534    3   30]
 [ 852    2   36]]
Datos escalados:
 [[1.         1.         1.        ]
 [0.6730038  0.6        0.88888889]
 [0.72908745 0.6        0.66666667]
 [0.40494297 0.4        0.8       ]]
valores maximos de cada caracteristica:
 [2104    5   45]


In [18]:
def mean_normalization(X):
    # 1. Calculamos estadísticas
    x_mean = np.mean(X, axis=0)
    x_max = np.max(X, axis=0)
    x_min = np.min(X, axis=0)
    
    # 2. Calculamos el rango
    rango = x_max - x_min
    
    # 3. Corrección: Si todos los datos de la columna son iguales, rango es 0
    rango_copy = np.copy(rango)
    rango_copy[rango_copy == 0] = 1 
    
    # 4. Operación: (X - Media) / Rango
    X_norm = (X - x_mean) / rango_copy
    
    return X_norm, x_mean, rango
    
X = np.array([
    [2104, 5, 45],
    [1416, 3, 40],
    [1534, 3, 30],
    [852, 2, 36]
])

valores_reescalados, media, rango = mean_normalization(X)
print("Datos originales:\n", X)
print("Datos escalados:\n", valores_reescalados)
print("Media de cada caracteristica:\n", media)
print("Rango:\n", rango)

Datos originales:
 [[2104    5   45]
 [1416    3   40]
 [1534    3   30]
 [ 852    2   36]]
Datos escalados:
 [[ 0.50119808  0.58333333  0.48333333]
 [-0.04832268 -0.08333333  0.15      ]
 [ 0.04592652 -0.08333333 -0.51666667]
 [-0.49880192 -0.41666667 -0.11666667]]
Media de cada caracteristica:
 [1476.5     3.25   37.75]
Rango:
 [1252    3   15]


In [19]:
def zscore_normalization(X):
    # 1. Calculamos media y desviación estándar
    x_mean = np.mean(X, axis=0)
    x_std = np.std(X, axis=0)
    
    # 2. Corrección: Si no hay dispersión (std=0), evitamos error
    x_std_copy = np.copy(x_std)
    x_std_copy[x_std_copy == 0] = 1
    
    # 3. Operación: (X - Media) / Desviación Estándar
    X_zscore = (X - x_mean) / x_std_copy
    
    return X_zscore, x_mean, x_std

X = np.array([
    [2104, 5, 45],
    [1416, 3, 40],
    [1534, 3, 30],
    [852, 2, 36]
])

valores_reescalados, media, desviacion_estandar = zscore_normalization(X)
print("Datos originales:\n", X)
print("Datos escalados:\n", valores_reescalados)
print("Media de cada caracteristica:\n", media)
print("Desviacion estandar de cada caracteristica:\n", desviacion_estandar)

Datos originales:
 [[2104    5   45]
 [1416    3   40]
 [1534    3   30]
 [ 852    2   36]]
Datos escalados:
 [[ 1.41133964  1.60591014  1.31954569]
 [-0.13607338 -0.22941573  0.40951418]
 [ 0.12932594 -0.22941573 -1.41054884]
 [-1.4045922  -1.14707867 -0.31851103]]
Media de cada caracteristica:
 [1476.5     3.25   37.75]
Desviacion estandar de cada caracteristica:
 [444.613034     1.08972474   5.49431524]
